kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: random-fail
spec:
  metrics:
  - name: random-fail
    count: 20
    interval: 20s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: curlimages/curl
                command:
                - curl
                - -i
                - http://hello-world-svc.default.svc.cluster.local:8081
              restartPolicy: Never
          activeDeadlineSeconds: 30
          ttlSecondsAfterFinished: 10
          backoffLimit: 1
