apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  strategy:
    canary:
      analysis:
        templates:
        - templateName: random-fail
      steps:
      - setWeight: 10
      - pause: {duration: 30s}
      - setWeight: 25
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 1m}
      - setWeight: 60
      - pause: {duration: 90s}
      - setWeight: 80
      - pause: {duration: 90s}
      - setWeight: 90
      - pause: {duration: 2m}
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: go-sample-app:2.0.0
        imagePullPolicy: Never
        name: hello-world
        resources:
          limits:
            memory: 50Mi
            cpu: 5m
          requests:
            memory: 50Mi
            cpu: 5m
        env:
        - name: PORT
          value: "8081"
        - name: MESSAGE
          value: "Hello, this is a test!!"
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
