apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: go-sample-app:alpine
        imagePullPolicy: Never
        name: hello-world
        env:
        - name: PORT
          value: "8081"
        - name: MESSAGE
          value: "Hello, this is a test!!"
        ports:
        - containerPort: 80
