apiVersion: batch/v1
kind: Job
metadata:
  name: normal-job
  # annotations:
  #   argocd.argoproj.io/hook: Sync
  #   argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - date; echo Hello, this is testing && exit 1
      restartPolicy: Never
