apiVersion: batch/v1
kind: Job
metadata:
  generateName: normal-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - date; echo Hello from test
      restartPolicy: Never
