apiVersion: batch/v1
kind: Job
metadata:
  name: normal-job
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - date; echo Hello
      restartPolicy: Never
