apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world-svc
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
  type: LoadBalancer
