apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world-svc
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: http
  selector:
    app: hello-world
  type: LoadBalancer
